# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Dell\Documents\GitHub\NSTL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Dell\Documents\GitHub\NSTL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"D:\software\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Dell\Documents\GitHub\NSTL\CMakeFiles C:\Users\Dell\Documents\GitHub\NSTL\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Dell\Documents\GitHub\NSTL\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f CMakeFiles\gtest.dir\build.make CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f CMakeFiles\gtest_main.dir\build.make CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named abc

# Build rule for target.
abc: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 abc
.PHONY : abc

# fast build rule for target.
abc/fast:
	$(MAKE) -f CMakeFiles\abc.dir\build.make CMakeFiles/abc.dir/build
.PHONY : abc/fast

gtest/googletest/src/gtest-all.obj: gtest/googletest/src/gtest-all.cc.obj

.PHONY : gtest/googletest/src/gtest-all.obj

# target to build an object file
gtest/googletest/src/gtest-all.cc.obj:
	$(MAKE) -f CMakeFiles\gtest.dir\build.make CMakeFiles/gtest.dir/gtest/googletest/src/gtest-all.cc.obj
.PHONY : gtest/googletest/src/gtest-all.cc.obj

gtest/googletest/src/gtest-all.i: gtest/googletest/src/gtest-all.cc.i

.PHONY : gtest/googletest/src/gtest-all.i

# target to preprocess a source file
gtest/googletest/src/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles\gtest.dir\build.make CMakeFiles/gtest.dir/gtest/googletest/src/gtest-all.cc.i
.PHONY : gtest/googletest/src/gtest-all.cc.i

gtest/googletest/src/gtest-all.s: gtest/googletest/src/gtest-all.cc.s

.PHONY : gtest/googletest/src/gtest-all.s

# target to generate assembly for a file
gtest/googletest/src/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles\gtest.dir\build.make CMakeFiles/gtest.dir/gtest/googletest/src/gtest-all.cc.s
.PHONY : gtest/googletest/src/gtest-all.cc.s

gtest/googletest/src/gtest_main.obj: gtest/googletest/src/gtest_main.cc.obj

.PHONY : gtest/googletest/src/gtest_main.obj

# target to build an object file
gtest/googletest/src/gtest_main.cc.obj:
	$(MAKE) -f CMakeFiles\gtest_main.dir\build.make CMakeFiles/gtest_main.dir/gtest/googletest/src/gtest_main.cc.obj
.PHONY : gtest/googletest/src/gtest_main.cc.obj

gtest/googletest/src/gtest_main.i: gtest/googletest/src/gtest_main.cc.i

.PHONY : gtest/googletest/src/gtest_main.i

# target to preprocess a source file
gtest/googletest/src/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles\gtest_main.dir\build.make CMakeFiles/gtest_main.dir/gtest/googletest/src/gtest_main.cc.i
.PHONY : gtest/googletest/src/gtest_main.cc.i

gtest/googletest/src/gtest_main.s: gtest/googletest/src/gtest_main.cc.s

.PHONY : gtest/googletest/src/gtest_main.s

# target to generate assembly for a file
gtest/googletest/src/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles\gtest_main.dir\build.make CMakeFiles/gtest_main.dir/gtest/googletest/src/gtest_main.cc.s
.PHONY : gtest/googletest/src/gtest_main.cc.s

test/list.obj: test/list.cpp.obj

.PHONY : test/list.obj

# target to build an object file
test/list.cpp.obj:
	$(MAKE) -f CMakeFiles\abc.dir\build.make CMakeFiles/abc.dir/test/list.cpp.obj
.PHONY : test/list.cpp.obj

test/list.i: test/list.cpp.i

.PHONY : test/list.i

# target to preprocess a source file
test/list.cpp.i:
	$(MAKE) -f CMakeFiles\abc.dir\build.make CMakeFiles/abc.dir/test/list.cpp.i
.PHONY : test/list.cpp.i

test/list.s: test/list.cpp.s

.PHONY : test/list.s

# target to generate assembly for a file
test/list.cpp.s:
	$(MAKE) -f CMakeFiles\abc.dir\build.make CMakeFiles/abc.dir/test/list.cpp.s
.PHONY : test/list.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... list_install_components
	@echo ... gtest
	@echo ... gtest_main
	@echo ... abc
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... install/strip
	@echo ... gtest/googletest/src/gtest-all.obj
	@echo ... gtest/googletest/src/gtest-all.i
	@echo ... gtest/googletest/src/gtest-all.s
	@echo ... gtest/googletest/src/gtest_main.obj
	@echo ... gtest/googletest/src/gtest_main.i
	@echo ... gtest/googletest/src/gtest_main.s
	@echo ... test/list.obj
	@echo ... test/list.i
	@echo ... test/list.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

